import { test, expect } from '@playwright/test'

test('input validation, duplicate resolution, persistence and editing', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Tạo spinner' })).toBeDisabled()
  await page.getByLabel('Danh sách của bạn').fill('  Đọc sách\n\nTập thể dục\nđọc sách')
  await expect(page.getByText('Có 1 dòng trùng.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tạo spinner' })).toBeDisabled()
  await page.getByRole('button', { name: 'Gộp dòng trùng' }).click()
  await page.reload()
  await expect(page.getByLabel('Danh sách của bạn')).toHaveValue('Đọc sách\nTập thể dục')
  await page.getByRole('button', { name: 'Tạo spinner' }).click()
  await page.getByRole('button', { name: 'Sửa danh sách' }).click()
  await expect(page.getByLabel('Danh sách của bạn')).toHaveValue('Đọc sách\nTập thể dục')
})

test('actual animation lands on the reported row and locks duplicate spins', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.screenshot({ path: 'test-results/setup-desktop.png', fullPage: true })
  await page.getByLabel('Danh sách của bạn').fill('NEWSLETTER\nYT KIDS CHANNEL\nDROPSHIPPING\nMETA ADS\nTRADING\nWEBSITE DESIGN')
  await page.getByRole('button', { name: 'Tạo spinner' }).click()
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click()
  await page.getByRole('radio', { name: '3s Nhanh' }).check()
  await page.getByRole('button', { name: 'Xong', exact: true }).click()
  await page.getByRole('button', { name: 'QUAY', exact: true }).click()
  await expect(page.getByRole('button', { name: 'ĐANG QUAY' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Sửa danh sách' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Cài đặt', exact: true })).toBeDisabled()
  await expect(page.locator('.winner-label')).toBeVisible({ timeout: 7000 })
  const alignment = await page.evaluate(() => {
    const frame = document.querySelector('.selection-frame')!.getBoundingClientRect()
    const center = frame.y + frame.height / 2
    const row = [...document.querySelectorAll('.reel-row')].find(el => { const r = el.getBoundingClientRect(); return Math.abs(r.y + r.height / 2 - center) < 1 })
    return { displayed: row?.textContent, selected: document.querySelector('.winner-label strong')?.textContent }
  })
  expect(alignment.displayed).toBeTruthy()
  expect(alignment.displayed).toBe(alignment.selected)
  await page.screenshot({ path: 'test-results/spinner-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'QUAY LẠI', exact: true }).click()
  await expect(page.locator('.winner-label')).toBeVisible({ timeout: 7000 })
  expect(errors).toEqual([])
})

test('no-repeat exhausts the pool, resets and respects the settings modal', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByLabel('Danh sách của bạn').fill('Một\nHai\nBa')
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click()
  await page.getByRole('switch', { name: 'Không lặp kết quả', exact: false }).check()
  await page.getByRole('button', { name: 'Xong', exact: true }).click()
  await page.getByRole('button', { name: 'Tạo spinner' }).click()
  const winners: string[] = []
  for (let i = 0; i < 3; i++) {
    await page.getByRole('button', { name: i === 0 ? 'QUAY' : 'QUAY LẠI', exact: true }).click()
    await expect(page.locator('.winner-label')).toBeVisible({ timeout: 7000 })
    winners.push(await page.locator('.winner-label strong').innerText())
  }
  expect(new Set(winners).size).toBe(3)
  await page.getByRole('button', { name: 'Đặt lại lượt quay', exact: true }).click()
  await expect(page.getByRole('button', { name: 'QUAY', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click()
  await page.keyboard.press('Space')
  await expect(page.locator('.is-spinning')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.locator('h1').click()
  await page.keyboard.press('Space')
  await expect(page.locator('.winner-label')).toBeVisible({ timeout: 7000 })
})

test('mobile layout handles long Vietnamese values and saves settings', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.screenshot({ path: 'test-results/setup-mobile.png', fullPage: true })
  await page.getByLabel('Danh sách của bạn').fill('Dành thời gian đọc một cuốn sách yêu thích và ghi lại những điều thú vị trong ngày hôm nay\nĐi dạo')
  await page.getByRole('button', { name: 'Tạo spinner' }).click()
  await page.getByRole('button', { name: 'QUAY', exact: true }).click()
  await expect(page.locator('.winner-label')).toBeVisible({ timeout: 7000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/spinner-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click()
  await page.getByRole('radio', { name: '5s Hồi hộp' }).check()
  await page.screenshot({ path: 'test-results/settings-mobile.png', fullPage: true })
  await page.keyboard.press('Escape')
  await page.reload()
  await page.getByRole('button', { name: 'Cài đặt', exact: true }).click()
  await expect(page.getByRole('radio', { name: '5s Hồi hộp' })).toBeChecked()
})
